FROM node:16.20.2@sha256:9096e122b56e434bfa963f161417cf61637b31d9fdfd5d68c411ceb0d962ffe4 as build

WORKDIR /app

COPY package.json /app

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

FROM nginxinc/nginx-unprivileged:alpine3.18@sha256:b2302acc7ca12f31a934bc64aa9f9c8080a5cabd8dd8b408c0b37c38006a595e

COPY --from=build /app/build /usr/share/nginx/html



EXPOSE 8080

CMD [ "nginx", "-g", "daemon off;" ]